### ISSUE TITLE
[Suggestion] Fuse OpenLock and ClosedLock

### ISSUE THREAD

**Issue by lionirdeadman** [elijabesu/SauriCogs#1]
These two should probably fused since they offer the same functionality but 2 different scenarios and could probably be handled with a configuration option.

**Comment by elijabesu** [comment]
Indeed, will merge them either today or tomorrow.

**Comment by elijabesu** [comment]
Done. Deleted both `closedlock` and `openlock`, replaced them with `lock` ^^
