### ISSUE TITLE
[Gallery] Bot doesn't respond to commands

### ISSUE THREAD

**Issue by DragoPrime** [elijabesu/SauriCogs#100]
Bot doesn't add any channels as gallery. This error in logs:
![chrome_kx4gJkjKeu](https://user-images.githubusercontent.com/99618256/225378209-be1afb3f-0f44-4f82-b4cb-f486e4c3195a.png)

**Comment by Khapra** [comment]
I'm having the same issue with the same error.

**Comment by Khapra** [comment]
The Gallery cog seems to work fine now. Try !galleryset add <channel>

**Comment by DragoPrime** [comment]
It works, thanks. Might want to update commands in help page.
