### ISSUE TITLE
[userlog] - Redbot 3.5.1 update broke the userlog system

### ISSUE THREAD

**Issue by freakexeuLow** [elijabesu/SauriCogs#102]
`[16:39:33] WARNING  [py.warnings] /home/redbot/.local/share/Red-DiscordBot/data/zzkbot/cogs/CogManager/cogs/userlog/__init__.py:5: RuntimeWarning: coroutine 'Red.add_cog' was never awaited
  bot.add_cog(UserLog(bot))

           ERROR    [red] Package loading failed
╭────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────╮
│ /home/redbot/redenv/lib/python3.9/site-packages/redbot/core/core_commands.py:188 in _load                                                                     │
│ ❱  188                 await bot.load_extension(spec)                                                                                                         │
│ /home/redbot/redenv/lib/python3.9/site-packages/redbot/core/bot.py:1686 in load_extension                                                                     │
│ ❱ 1686             await lib.setup(self)                                                                                                                      │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: object NoneType can't be used in 'await' expression`

**Comment by rex2630** [comment]
this is fixed on dpy2 branch. It just wasnt reflected to master just yet

**Comment by freakexeuLow** [comment]
> this is fixed on dpy2 branch. It just wasnt reflected to master just yet

thank you, did not know that....works now :)

**Comment by freakexeuLow** [comment]
Okay, I have to open the ticket because the join messages don't work (only the leave messages work)....no errors are reported when i starting the plugin, only the join message does not work
![40889560686fb6e8281a070d2f4c3fc1](https://github.com/elijabesu/SauriCogs/assets/32603929/a3666c19-df63-44bb-ae1e-19c026a10f27)
![31183cbbd85d4c6b3307b360e3c45dd6](https://github.com/elijabesu/SauriCogs/assets/32603929/623bf3fe-1960-43d4-b988-f76a512ea20f)

**Comment by nizzan** [comment]
I have seen the same, that only the leave message works.
This seems to be the errorlog from when the join message fails.

```
[2023-07-02 04:09:07] [ERROR] discord.client: Ignoring exception in on_member_join
redbot  | Traceback (most recent call last):
redbot  |   File "/data/venv/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
redbot  |     await coro(*args, **kwargs)
redbot  |   File "/data/cogs/CogManager/cogs/userlog/userlog.py", line 109, in on_member_join
redbot  |     since_created = (time - member.created_at).days
redbot  |                      ~~~~~^~~~~~~~~~~~~~~~~~~
redbot  | TypeError: can't subtract offset-naive and offset-aware datetimes

```

**Comment by freakexeuLow** [comment]
@nizzan did you fix it in your last branch? [asdf6](https://github.com/elijabesu/SauriCogs/pull/103/commits/b37f07ab165450d9f86ce965d9b89962e892ce4f)

NVM: it works, thanks for your time 👍🏼
