### ISSUE TITLE
[Issue] Suggestion cog wont load

### ISSUE THREAD

**Issue by cj2tech** [elijabesu/SauriCogs#105]
error in console when trying to load suggestion cog

[WARNING] py.warnings: /data/cogs/CogManager/cogs/suggestion/__init__.py:5: RuntimeWarning: coroutine 'Red.add_cog' was never awaited
  bot.add_cog(Suggestion(bot))
[2023-09-14 09:54:06] [ERROR] red: Package loading failed
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 188, in _load
    await bot.load_extension(spec)
  File "/data/venv/lib/python3.11/site-packages/redbot/core/bot.py", line 1686, in load_extension
    await lib.setup(self)
TypeError: object NoneType can't be used in 'await' expression

**Comment by cswimr** [comment]
You're using the legacy version of SauriCogs with a Red 3.5+ installation. Please uninstall the Suggestion cog and re-add the repository with the following commands:
`[p]cog uninstall suggestion`
`[p]repo remove SauriCogs`
`[p]repo add SauriCogs https://github.com/elijabesu/SauriCogs dpy2`
`[p]cog install SauriCogs suggestion`
`[p]load suggestion`

**Comment by cj2tech** [comment]
This fixed my issue thanks
