### ISSUE TITLE
[Suggestion] Unique Name; Message moderator's channel

### ISSUE THREAD

**Issue by JoeKoen** [elijabesu/SauriCogs#11]
If possible, can we have something where the cog leaves a message in a certain channel to tell mods/admins certain users tried to use their name? That would be a cool thing to have.

**Comment by elijabesu** [comment]
Should it be like a mod log case or something simpler?

**Comment by JoeKoen** [comment]
Was thinking something more similar, something like

`!unset channel #alerts `

And a message pops up like this
![image](https://user-images.githubusercontent.com/19499442/75546033-bbbff300-59f5-11ea-9513-7a5bb75ce6e6.png)

Simple and easy text,
But something like

```
UniqueName:
Has Renamed user [UserID] from copying a moderator's name [Mod's Nick]
```


Or if mod log is easier to do, but either way, This would be nice to have. 

I've been using the plugin for a week now, and it already works well, just the emebds get gobbled in the logs from logging allot of user actions.

**Comment by elijabesu** [comment]
Should be fixed. If no, feel free to comment here and I will reopen this :)
