### ISSUE TITLE
[Suggestion] Daily cookie

### ISSUE THREAD

**Issue by Nieczysty** [elijabesu/SauriCogs#12]
Hi
It would be cool if specific could rank gets more of daily cookies.
I mean we have 3 diffrent ranks: 
Normal rank gets 2 cookies per day,
Better rank gets 4 cookies per day,
Much Better rank gets 6 cookies per day.

**Comment by elijabesu** [comment]
Will add it as a command to change role's multiplier. But it would be disabled when the random amount is enabled.

**Comment by elijabesu** [comment]
Should be fixed. If no, feel free to comment here and I will reopen this :)
