### ISSUE TITLE
[Suggestion] Red currency to cookies

### ISSUE THREAD

**Issue by Nieczysty** [elijabesu/SauriCogs#13]
I think it could be cool to add possibility to buy cookies using defualt red economy. 
For example i have 12k (of my local currency) and i can exchange it for 2k of cookies.
All could be done by cookiestore.

**Comment by elijabesu** [comment]
Will add this to Cookies cog, it makes more sense to me (tho I'm still contemplating)

**Comment by elijabesu** [comment]
Should be fixed. If no, feel free to comment here and I will reopen this :)
