### ISSUE TITLE
[Suggestion] Suggestion

### ISSUE THREAD

**Issue by Menteroth** [elijabesu/SauriCogs#14]
Maybe an option to set your own reaction icons if you don't want to use the regular marks that Discord has, `:white_check_mark:` and `:negative_squared_cross_mark:`.

**Comment by elijabesu** [comment]
Would it include custom emojis or just unicode (aka emojipedia)? Because custom ones would make it significantly more time consuming for me.

**Comment by Menteroth** [comment]
Was just thinking custom ones that you add to a Discord server. Wouldn't know about that other choice. I guess you could go for whatever is easier for yourself and if you wanted to add it. Just a small thing I thought of.

**Comment by elijabesu** [comment]
Should be done. If it doesn't work, feel free to comment here and I will reopen this :)
