### ISSUE TITLE
[Marriage] Perform Reply

### ISSUE THREAD

**Issue by Menteroth** [elijabesu/SauriCogs#15]
`perform fuck member`
You can't give an answer with punctuation after.

**Comment by elijabesu** [comment]
That's on redbot and not me. I use the yes_or_no predicate which, according to [Red docs](https://red-discordbot.readthedocs.io/en/stable/framework_utils.html#redbot.core.utils.predicates.MessagePredicate.yes_or_no), is 

> Match if the message is “yes”/”y” or “no”/”n”.

And I do not intend on writing my own class method just because of a dot
