### ISSUE TITLE
[UniqueName] Message is a template response

### ISSUE THREAD

**Issue by cyberofficial** [elijabesu/SauriCogs#18]
When a forbidden name is found, there is no info is there; but a template response

Latest RedBot build

![image](https://user-images.githubusercontent.com/19499442/79408632-cc0e3c00-7f69-11ea-9bee-2af8e04740d7.png)

-----------

```py
                warning_text = """**Unique Name warning:**
                
                Discovered a forbidden name: '{}'. 
                User: {} - `{}#{} ({})`"""
                await channel.send(warning_text.format(after.name,after.mention,after.name,after.discriminator,after.id))
```

Fixing the code up some, when it runs, it says random names

**Comment by elijabesu** [comment]
It should be fixed now! If not, let me know and I can reopen this :)
