### ISSUE TITLE
[Application] Optional role to accept and deny applicants

### ISSUE THREAD

**Issue by Brandjuh** [elijabesu/SauriCogs#26]
Hey hey,

At the moment only admins are able to handle the applications, however I recently got someone that has a dedicated role for people that are handling those applications. 

Hence why I want to request a option to add a role that is allowed to handle those applications beside the admins.

Do you want to  implement this? Otherwise I open a bounty on the cogboard for a costume one.

Thanks!

**Comment by elijabesu** [comment]
Hey, I can add that feature tomorrow. And if not tomorrow, then next week, depending on my time

**Comment by Brandjuh** [comment]
Would be awesome, thank you

Op za 30 mei 2020 om 20:14 schreef Ellie <notifications@github.com>:

**Comment by elijabesu** [comment]
Should be added and functional with the commit ^. If not, let me know and I will reopen this :)
