### ISSUE TITLE
[Request] forwarding antispam 

### ISSUE THREAD

**Issue by Motzumoto** [elijabesu/SauriCogs#35]
it would be nice if this cog had an antispam feature, like a cooldown for specific users that gradually get longer and longer for repeating users. Or the ability to block them entirely.
![image](https://user-images.githubusercontent.com/45925152/89412938-eaa16a00-d6f5-11ea-8868-1b16a764f5bb.png)
Look at image posted to get what i mean
its really really annoying

**Comment by elijabesu** [comment]
Fixed with the merge ^
