### ISSUE TITLE
Amount paid not reflecting properly.

### ISSUE THREAD

**Issue by lramon18** [elijabesu/SauriCogs#37]
Example:
I have the set amount at 100, but it shows {end_amount} instead.
![image](https://user-images.githubusercontent.com/67785468/89747791-eb375900-da85-11ea-9187-734c38beaee8.png)

**Comment by elijabesu** [comment]
Hihi, it should now be fixed, I forgot an `f`. If there is any issue, lmk and I will reopen this issue.
