### ISSUE TITLE
[Forwarding] Says delivered but no actual message sent

### ISSUE THREAD

**Issue by LilyKame** [elijabesu/SauriCogs#38]
File redenv\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File \cogs\CogManager\cogs\forwarding\forwarding.py", line 79, in on_message
    await self._send_to(embed)
  File \cogs\CogManager\cogs\forwarding\forwarding.py", line 27, in _send_to
    await self.bot.is_owner(discord.Object(id=None))
  File lib\site-packages\discord\object.py", line 66, in __init__
    id = int(id)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by LilyKame** [comment]
Hello! It's still not operational, not too sure what you mean by the feedback needed label

**Comment by elijabesu** [comment]
It was mainly for me because I do not remember what the line was for and I currently do not have any RedBot hosted to test it on

**Comment by kreusada** [comment]
> It was mainly for me because I do not remember what the line was for and I currently do not have any RedBot hosted to test it on

Does this still need testing? Happy to help out with this

**Comment by elijabesu** [comment]
> Does this still need testing? Happy to help out with this
Y e a h, I kinda forgot about that, not gonna lie--

**Comment by elijabesu** [comment]
Fixed, `self.bot.owner_id` was changed into `self.bot.owner_ids` and I didn't know until today.
