### ISSUE TITLE
.setcookies rate less than 1?

### ISSUE THREAD

**Issue by vertyco** [elijabesu/SauriCogs#40]
I want cookies to be more valuable than economy credits :(
When i do .setcookies rate (anything less than 1) 
I get "Converting to "int" failed for parameter "rate"." and it makes me sad lol

(EDIT): nvm figured it out, went directly into the cog config file on the server and changed the rate in notepad :)

**Comment by elijabesu** [comment]
Oh shoot, I've never even noticed that

**Comment by elijabesu** [comment]
The command should work now
