### ISSUE TITLE
[Suggestion] For "suggestion" cog

### ISSUE THREAD

**Issue by atmos-o** [elijabesu/SauriCogs#41]
1. keep eye on `downemoji` & `upemoji` emote and allow a user to only react to one of them.

2. If repost after decision made is enabled, give option to not delete original suggestion. 
- also allow to edit original suggestion msg after decision is made and "repost suggestion" is enabled.

3. Tally votes and add it in as information in edited and reposted embed.

4. don't clear emotes from a suggestions original msg after decision is made to alloww & see who voted what (can stop tracking `downemoji` & `upemoji` emote here)

**Comment by elijabesu** [comment]
It should all be implemented in PR #46, I just need it tested before publishing.

**Comment by elijabesu** [comment]
Done! Should be all working :)
