### ISSUE TITLE
[SUGGESTION] "Application" Cog

### ISSUE THREAD

**Issue by Dragonias** [elijabesu/SauriCogs#42]
Hey there! It's me again!

So I am coming in here for this beautiful cog with a few suggestions the following being if possible:

1. Remove the need of a Role as a option
2. Customize how long the Applicant has per answer we sometimes get answers that take up to 5 minutes
3. And possible also allow to remove or customize Questions?

Thank you so much in Advance!

**Comment by elijabesu** [comment]
It _should_ be fixed with the commit referenced above. If there's any issue, do let me know and we can reopen this issue (or make a new one).
