### ISSUE TITLE
[Application] Bug in marriage cog

### ISSUE THREAD

**Issue by sp00nd** [elijabesu/SauriCogs#49]
I know it is simply cosmetic/for fun. 

If you have at least 1 of any gift, you are able to gift yourself the item to duplicate it. 
Very easy to replicate.

**X**: perform gift @ Y food
:gift: X has gifted one food to Y
Available gifts:
food - 1 pc

**Y**: perform gift @ Y food
:gift: Y has gifted one food to Y
Available gifts:
food - 2 pcs

**Comment by elijabesu** [comment]
Oh damn, that is kinda smart to do, I didn't think of that. Will fix it either today or tomorrow morning, thanks for reporting

**Comment by elijabesu** [comment]
Should be fixed now.

**Comment by sp00nd** [comment]
Actions and gifts are now showing with:

_You cannot perform anything with yourself!_

Thanks
