### ISSUE TITLE
Help regarding forking cookie cog for own purpose.

### ISSUE THREAD

**Issue by OhCrumbs** [elijabesu/SauriCogs#55]
Hey Sauri,

I love your cookie cog and have been using it for a while now, Just wondered if its possible if i can fork it and edit it to be something else instead of cookies.

Thank you for your time

Crumbs.

**Comment by elijabesu** [comment]
Hi, of course, I have no problem with forking or editing, as long as you keep my credits in ^^

**Comment by OhCrumbs** [comment]
Okay perfect could i get some help with editing? Credits would be kept in of course.

**Comment by elijabesu** [comment]
Sure. I will be opening a support Discord server in the following days, so I could help you properly there rather than over here.

**Comment by OhCrumbs** [comment]
perfect. all i really need is the cookie changed to coin and emoji changed to a custom one in the discord server if thats possible.

**Comment by OhCrumbs** [comment]
i have just tried editing all the words that are cookie to coin and cookies to coins and replace :cookie: to :dashcoin:

and when i try and load i get errors

**Comment by OhCrumbs** [comment]
Could you post discord invite link here to your support server once its created/setup. Thanks

**Comment by elijabesu** [comment]
Sorry, got carried away yesterday. The link is https://discord.gg/rrJVJddnVv
