### ISSUE TITLE
[ReactTickets] Invalid Reaction

### ISSUE THREAD

**Issue by Zenchaeus** [elijabesu/SauriCogs#61]
When I try to setup the reacttickets cog, it asks me to react on the message it sends. But when I try to add a reaction, it only says 'invalid reaction' no matter what reaction I add. I've tried reinstalling but still the same.

**Comment by XenonUnity** [comment]
You have to add the reaction on [p]ticketset case add

**Comment by Zenchaeus** [comment]
> You have to add the reaction on [p]ticketset case add. I got confused at first but I just messed about with commands and figured it out

Thanks! That seems to work. But still kinda weird though. I guess I can close this now.
