### ISSUE TITLE
[AdvancedLock] enable using role id in conjunction with role/channel name

### ISSUE THREAD

**Issue by skyguardian18** [elijabesu/SauriCogs#64]
Hey Sauri,
I just wanted to give input about advancedlock. Btw, it's an awesome cog, thank you!
I just find it sometimes easier to just put the role/channel id instead of the role/channel name when setting up the cog, especially I almost always forget the capital letters in my roles.

Thank you.

**Comment by elijabesu** [comment]
Hihi, it _should_ now accepts role IDs
