### ISSUE TITLE
[Suggestion] Feature request to be able to add attachments

### ISSUE THREAD

**Issue by Skyridr** [elijabesu/SauriCogs#66]
I love the suggestion cog! Would it be possible to include user attachments as well? Currently it appears to include any text, but any attachments (eg, images) added by the user isn't used by the cog.

Regards,
Skyrider

**Comment by elijabesu** [comment]
Hihi, done ^^ 
![image](https://user-images.githubusercontent.com/41390133/117417681-e28f8880-af1a-11eb-9a80-8edcf1c8c57d.png)

**Comment by elijabesu** [comment]
btw, it only allows one image per suggestion
