### ISSUE TITLE
[Reacttickets] Users can't see message history

### ISSUE THREAD

**Issue by Zenchaeus** [elijabesu/SauriCogs#70]
After a user opens a support ticket, they can only view the channel but don't have the 'read message history' permission. I tried setting it by default on the category but that doesn't work. Is there any way to fix this? So far, this is the best react ticket cog that I found. Really hope this bug can be fixed.

**Comment by elijabesu** [comment]
Fixed in commit linked above. If there are any issues, lmk and I'll reopen this.
