### ISSUE TITLE
[suggest] the cog spamming Ignoring exception in on_reaction_add

### ISSUE THREAD

**Issue by mina9999** [elijabesu/SauriCogs#72]
hi the cog keep spamming this error : 

Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Ignoring exception in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Traceback (most recent call last):
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     await coro(*args, **kwargs)
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/suggestion/suggestion.py", line 494, in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     if message.channel.id == await self.config.guild(message.guild).suggest_id():
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 976, in guild
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     return self._get_base_group(self.GUILD, str(guild.id))
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: AttributeError: 'NoneType' object has no attribute 'id'
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Ignoring exception in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Traceback (most recent call last):
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     await coro(*args, **kwargs)
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/suggestion/suggestion.py", line 494, in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     if message.channel.id == await self.config.guild(message.guild).suggest_id():
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 976, in guild
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     return self._get_base_group(self.GUILD, str(guild.id))
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: AttributeError: 'NoneType' object has no attribute 'id'
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Ignoring exception in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Traceback (most recent call last):
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     await coro(*args, **kwargs)
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/suggestion/suggestion.py", line 494, in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     if message.channel.id == await self.config.guild(message.guild).suggest_id():
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 976, in guild
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     return self._get_base_group(self.GUILD, str(guild.id))
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: AttributeError: 'NoneType' object has no attribute 'id'
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Ignoring exception in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Traceback (most recent call last):
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     await coro(*args, **kwargs)
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/suggestion/suggestion.py", line 494, in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     if message.channel.id == await self.config.guild(message.guild).suggest_id():
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 976, in guild
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     return self._get_base_group(self.GUILD, str(guild.id))
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: AttributeError: 'NoneType' object has no attribute 'id'
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Ignoring exception in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Traceback (most recent call last):
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     await coro(*args, **kwargs)
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/suggestion/suggestion.py", line 494, in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     if message.channel.id == await self.config.guild(message.guild).suggest_id():
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 976, in guild
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     return self._get_base_group(self.GUILD, str(guild.id))
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: AttributeError: 'NoneType' object has no attribute 'id'
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Ignoring exception in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Traceback (most recent call last):
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     await coro(*args, **kwargs)
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/suggestion/suggestion.py", line 494, in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     if message.channel.id == await self.config.guild(message.guild).suggest_id():
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 976, in guild
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     return self._get_base_group(self.GUILD, str(guild.id))
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: AttributeError: 'NoneType' object has no attribute 'id'
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Ignoring exception in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Traceback (most recent call last):
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     await coro(*args, **kwargs)
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/suggestion/suggestion.py", line 494, in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     if message.channel.id == await self.config.guild(message.guild).suggest_id():
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 976, in guild
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     return self._get_base_group(self.GUILD, str(guild.id))
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: AttributeError: 'NoneType' object has no attribute 'id'
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Ignoring exception in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Traceback (most recent call last):
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     await coro(*args, **kwargs)
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/suggestion/suggestion.py", line 494, in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     if message.channel.id == await self.config.guild(message.guild).suggest_id():
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 976, in guild
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     return self._get_base_group(self.GUILD, str(guild.id))
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: AttributeError: 'NoneType' object has no attribute 'id'
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Ignoring exception in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Traceback (most recent call last):
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     await coro(*args, **kwargs)
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/suggestion/suggestion.py", line 494, in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     if message.channel.id == await self.config.guild(message.guild).suggest_id():
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 976, in guild
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     return self._get_base_group(self.GUILD, str(guild.id))
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: AttributeError: 'NoneType' object has no attribute 'id'
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Ignoring exception in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Traceback (most recent call last):
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     await coro(*args, **kwargs)
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/suggestion/suggestion.py", line 494, in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     if message.channel.id == await self.config.guild(message.guild).suggest_id():
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 976, in guild
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     return self._get_base_group(self.GUILD, str(guild.id))
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: AttributeError: 'NoneType' object has no attribute 'id'
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Ignoring exception in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Traceback (most recent call last):
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     await coro(*args, **kwargs)
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/suggestion/suggestion.py", line 494, in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     if message.channel.id == await self.config.guild(message.guild).suggest_id():
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 976, in guild
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     return self._get_base_group(self.GUILD, str(guild.id))
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: AttributeError: 'NoneType' object has no attribute 'id'
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Ignoring exception in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Traceback (most recent call last):
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     await coro(*args, **kwargs)
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/suggestion/suggestion.py", line 494, in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     if message.channel.id == await self.config.guild(message.guild).suggest_id():
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 976, in guild
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     return self._get_base_group(self.GUILD, str(guild.id))
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: AttributeError: 'NoneType' object has no attribute 'id'
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Ignoring exception in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Traceback (most recent call last):
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     await coro(*args, **kwargs)
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/.local/share/Red-DiscordBot/data/candy/cogs/CogManager/cogs/suggestion/suggestion.py", line 494, in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     if message.channel.id == await self.config.guild(message.guild).suggest_id():
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 976, in guild
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     return self._get_base_group(self.GUILD, str(guild.id))
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: AttributeError: 'NoneType' object has no attribute 'id'
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Ignoring exception in on_reaction_add
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]: Traceback (most recent call last):
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:   File "/root/redenv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
Jul 28 11:10:03 vmi538808.contaboserver.net python[20371]:     await coro(*args, **kwargs)

**Comment by elijabesu** [comment]
It *could* potentially be fixed?
