### ISSUE TITLE
[Counting] Channel description way off

### ISSUE THREAD

**Issue by Dark-lame** [elijabesu/SauriCogs#91]
We have a dedicated counting channel with the channel description set to count with the users. So if anyone is confused on the next number they can read the channel descr. and move from there. However, the channel number is way off from the users' number. 
![image](https://user-images.githubusercontent.com/64549497/176014474-5d3bb556-49a6-4db2-9781-5717f3d80c16.png)
We have tried disabling and re-enabling the channel topic and deleting, but it still did not fix it. 
![image](https://user-images.githubusercontent.com/64549497/176014830-8f281b83-a669-4063-ae1a-598aa151ff01.png)
![image](https://user-images.githubusercontent.com/64549497/176014883-819038a8-c387-4f23-af98-9202477469b8.png)

As shown in the above images, the channel settings has the correct number, but not the channel description. Possible solution could be to make the channel description pull from the channel settings.

**Comment by elijabesu** [comment]
Hi, it should now take the number from settings. If the issue is still present, we can reopen this. :)
